import type {
  Coupon,
  DemoUser,
  Groomer,
  Pet,
  Review,
  Salon,
  Service,
} from "./types";

export const DEMO_USER: DemoUser = {
  name: "김하늘",
  email: "haneul@pawbeauty.demo",
  membership: "PawBeauty 멤버",
  emoji: "🙂",
};

export const SEED_PETS: Pet[] = [
  {
    id: "pet-1",
    name: "콩이",
    species: "dog",
    breed: "푸들",
    age: 3,
    weight: 4.2,
    emoji: "🐩",
    image: "/images/pets/pet-01-kongi.png",
    note: "겁이 많아요. 드라이어 소리에 예민해요.",
  },
  {
    id: "pet-2",
    name: "몽이",
    species: "dog",
    breed: "말티즈",
    age: 2,
    weight: 2.8,
    emoji: "🐶",
    image: "/images/pets/pet-02-mongi.png",
    note: "발 만지는 걸 싫어해요.",
  },
  {
    id: "pet-3",
    name: "보리",
    species: "cat",
    breed: "코리안숏헤어",
    age: 1,
    weight: 4.1,
    emoji: "🐱",
    image: "/images/pets/pet-03-bori.png",
    note: "낯가림이 있지만 금방 적응해요.",
  },
];

export const SERVICES: Service[] = [
  {
    id: "svc-1",
    name: "기본 미용",
    shortDesc: "목욕 + 기본 컷",
    desc: "목욕, 기본 클리핑, 발톱·귀 정리까지 포함된 기본 케어예요.",
    price: 45000,
    durationMin: 90,
    emoji: "✂️",
    popular: true,
  },
  {
    id: "svc-2",
    name: "스페셜 미용",
    shortDesc: "목욕 + 스타일 컷",
    desc: "곰돌이컷, 브로콜리컷 등 원하는 스타일로 가위컷을 진행해요.",
    price: 65000,
    durationMin: 120,
    emoji: "🎀",
    popular: true,
  },
  {
    id: "svc-3",
    name: "프리미엄 스파",
    shortDesc: "스파 + 딥 케어",
    desc: "탄산 스파와 아로마 마사지로 피부와 모질을 깊이 케어해요.",
    price: 80000,
    durationMin: 150,
    emoji: "🛁",
  },
  {
    id: "svc-4",
    name: "부분 관리",
    shortDesc: "발톱/귀/위생",
    desc: "발톱, 귀 청소, 위생 부위 정리만 빠르게 받아보세요.",
    price: 20000,
    durationMin: 30,
    emoji: "🐾",
  },
  {
    id: "svc-5",
    name: "고양이 미용",
    shortDesc: "고양이 전문 케어",
    desc: "고양이 전문 미용사가 스트레스를 최소화하며 케어해요.",
    price: 60000,
    durationMin: 100,
    emoji: "🐈",
  },
  {
    id: "svc-6",
    name: "약욕 & 피부 케어",
    shortDesc: "피부 진정 목욕",
    desc: "피부가 예민한 아이를 위한 저자극 약욕 프로그램이에요.",
    price: 50000,
    durationMin: 70,
    emoji: "🌿",
  },
];

export const SALONS: Salon[] = [
  {
    id: "salon-1",
    name: "살롱 드 포우",
    rating: 4.9,
    reviewCount: 324,
    distanceKm: 0.4,
    priceFrom: 45000,
    availableToday: true,
    tags: ["소형견 전문", "1:1 케어", "예약제"],
    address: "서울 강남구 청담동 12-3",
    openHours: "09:00 - 19:00",
    emoji: "🐩",
    gradient: "from-mint-100 to-mint-200",
    image: "/images/salons/salon-01-salon-de-paw.png",
  },
  {
    id: "salon-2",
    name: "멍뭉살롱",
    rating: 4.8,
    reviewCount: 218,
    distanceKm: 0.9,
    priceFrom: 40000,
    availableToday: true,
    tags: ["대형견 가능", "주차 편리"],
    address: "서울 서초구 서초동 45-1",
    openHours: "10:00 - 20:00",
    emoji: "🐕",
    gradient: "from-cream-200 to-cream-300",
    image: "/images/salons/salon-02-meongmong-salon.png",
  },
  {
    id: "salon-3",
    name: "포근포근 펫살롱",
    rating: 4.7,
    reviewCount: 156,
    distanceKm: 1.2,
    priceFrom: 38000,
    availableToday: false,
    tags: ["노령견 케어", "저소음 드라이"],
    address: "서울 서초구 잠원동 8-2",
    openHours: "09:30 - 18:30",
    emoji: "🧸",
    gradient: "from-coral-100 to-coral-200",
    image: "/images/salons/salon-03-pogeunpogeun-pet-salon.png",
  },
  {
    id: "salon-4",
    name: "코코 펫뷰티",
    rating: 4.9,
    reviewCount: 287,
    distanceKm: 1.6,
    priceFrom: 50000,
    availableToday: true,
    tags: ["스파 전문", "프리미엄"],
    address: "서울 서초구 방배동 77-5",
    openHours: "10:00 - 19:00",
    emoji: "💆",
    gradient: "from-mint-100 to-cream-200",
    image: "/images/salons/salon-04-coco-pet-beauty.png",
  },
  {
    id: "salon-5",
    name: "해피테일",
    rating: 4.6,
    reviewCount: 132,
    distanceKm: 2.1,
    priceFrom: 35000,
    availableToday: true,
    tags: ["가성비", "당일 예약"],
    address: "서울 강남구 논현동 31-9",
    openHours: "09:00 - 18:00",
    emoji: "🐾",
    gradient: "from-cream-100 to-mint-100",
    image: "/images/salons/salon-05-happy-tail.png",
  },
  {
    id: "salon-6",
    name: "캣살롱 모모",
    rating: 4.8,
    reviewCount: 194,
    distanceKm: 2.8,
    priceFrom: 55000,
    availableToday: false,
    tags: ["고양이 전문", "무마취 미용"],
    address: "서울 강남구 역삼동 102-4",
    openHours: "11:00 - 20:00",
    emoji: "🐱",
    gradient: "from-coral-50 to-cream-200",
    image: "/images/salons/salon-06-cat-salon-momo.png",
  },
];

export const GROOMERS: Groomer[] = [
  {
    id: "grm-1",
    salonId: "salon-1",
    name: "이수진",
    careerYears: 7,
    rating: 4.9,
    reviewCount: 124,
    specialties: ["푸들 스타일컷", "소형견"],
    intro: "겁 많은 아이도 편안하게, 차분한 케어를 약속해요.",
    premium: true,
    emoji: "👩🏻‍🦰",
    image: "/images/groomers/groomer-03-lee-sujin.png",
  },
  {
    id: "grm-2",
    salonId: "salon-1",
    name: "김나연",
    careerYears: 5,
    rating: 4.8,
    reviewCount: 98,
    specialties: ["가위컷", "말티즈"],
    intro: "섬세한 가위컷으로 얼굴 라인을 살려드려요.",
    emoji: "👩🏻",
  },
  {
    id: "grm-3",
    salonId: "salon-1",
    name: "박지훈",
    careerYears: 6,
    rating: 4.7,
    reviewCount: 76,
    specialties: ["스포팅컷", "중형견"],
    intro: "빠르고 안정적인 미용으로 아이 부담을 줄여요.",
    emoji: "👨🏻",
  },
  {
    id: "grm-4",
    salonId: "salon-2",
    name: "최은영",
    careerYears: 8,
    rating: 4.9,
    reviewCount: 143,
    specialties: ["대형견", "피부 케어"],
    intro: "대형견 미용 경력 8년, 힘들어하지 않게 케어해요.",
    premium: true,
    emoji: "👩🏻‍🦱",
    image: "/images/groomers/groomer-01-choi-eunyoung.png",
  },
  {
    id: "grm-5",
    salonId: "salon-2",
    name: "정민호",
    careerYears: 4,
    rating: 4.6,
    reviewCount: 61,
    specialties: ["기본 미용", "위생 미용"],
    intro: "기본에 충실한 꼼꼼한 미용을 해드려요.",
    emoji: "🧑🏻",
  },
  {
    id: "grm-6",
    salonId: "salon-3",
    name: "한지원",
    careerYears: 9,
    rating: 4.8,
    reviewCount: 112,
    specialties: ["노령견 케어", "저자극 미용"],
    intro: "나이 든 아이의 컨디션에 맞춰 천천히 진행해요.",
    premium: true,
    emoji: "👩🏻‍🦳",
    image: "/images/groomers/groomer-04-han-jiwon.png",
  },
  {
    id: "grm-7",
    salonId: "salon-3",
    name: "오세림",
    careerYears: 3,
    rating: 4.5,
    reviewCount: 44,
    specialties: ["부분 미용", "목욕"],
    intro: "아이와 교감하며 즐거운 목욕 시간을 만들어요.",
    emoji: "👧🏻",
  },
  {
    id: "grm-8",
    salonId: "salon-4",
    name: "강다현",
    careerYears: 6,
    rating: 4.9,
    reviewCount: 137,
    specialties: ["스파 테라피", "아로마 케어"],
    intro: "스파 전문가의 손길로 피부 속부터 건강하게.",
    premium: true,
    emoji: "👩🏻‍⚕️",
    image: "/images/groomers/groomer-02-kang-dahyun.png",
  },
  {
    id: "grm-9",
    salonId: "salon-4",
    name: "임서연",
    careerYears: 5,
    rating: 4.7,
    reviewCount: 89,
    specialties: ["머드팩", "모질 개선"],
    intro: "푸석한 털도 윤기 나게, 모질 개선 전문이에요.",
    emoji: "👩🏻‍🎨",
  },
  {
    id: "grm-10",
    salonId: "salon-5",
    name: "조현우",
    careerYears: 4,
    rating: 4.6,
    reviewCount: 58,
    specialties: ["기본 미용", "당일 케어"],
    intro: "합리적인 가격으로 깔끔한 미용을 해드려요.",
    emoji: "👨🏻‍🦱",
  },
  {
    id: "grm-11",
    salonId: "salon-5",
    name: "배소민",
    careerYears: 2,
    rating: 4.5,
    reviewCount: 31,
    specialties: ["목욕", "위생 미용"],
    intro: "아이 눈높이에서 다정하게 케어해드려요.",
    emoji: "👩🏻‍🦲",
  },
  {
    id: "grm-12",
    salonId: "salon-6",
    name: "윤가을",
    careerYears: 6,
    rating: 4.8,
    reviewCount: 104,
    specialties: ["고양이 전문", "무마취 미용"],
    intro: "고양이의 스트레스 신호를 읽으며 진행해요.",
    premium: true,
    emoji: "👩🏻‍🔬",
  },
  {
    id: "grm-13",
    salonId: "salon-6",
    name: "신예린",
    careerYears: 4,
    rating: 4.7,
    reviewCount: 67,
    specialties: ["장모종 고양이", "브러싱 케어"],
    intro: "엉킨 털도 아프지 않게 살살 풀어드려요.",
    emoji: "👩🏻‍💼",
  },
];

export const REVIEWS: Review[] = [
  {
    id: "rev-1",
    salonId: "salon-1",
    author: "김하늘",
    petName: "콩이",
    rating: 5,
    content:
      "겁 많은 콩이가 처음으로 안 떨고 미용을 받았어요. 이수진 선생님 최고예요!",
    date: "2026-08-18",
    serviceName: "기본 미용",
  },
  {
    id: "rev-2",
    salonId: "salon-1",
    author: "박서준",
    petName: "두부",
    rating: 5,
    content: "곰돌이컷 요청했는데 사진보다 더 귀엽게 나왔어요. 재방문 의사 100%!",
    date: "2026-08-15",
    serviceName: "스페셜 미용",
  },
  {
    id: "rev-3",
    salonId: "salon-1",
    author: "이지은",
    petName: "라떼",
    rating: 4,
    content: "예약제라 대기 없이 바로 진행돼서 좋았어요. 마무리도 깔끔합니다.",
    date: "2026-08-11",
    serviceName: "기본 미용",
  },
  {
    id: "rev-4",
    salonId: "salon-2",
    author: "최민준",
    petName: "초코",
    rating: 5,
    content:
      "리트리버라 미용실 찾기 힘들었는데 대형견도 정성껏 해주셔서 감동했어요.",
    date: "2026-08-17",
    serviceName: "기본 미용",
  },
  {
    id: "rev-5",
    salonId: "salon-2",
    author: "정유진",
    petName: "봄이",
    rating: 4,
    content: "주차가 편해서 좋아요. 미용 후 사진도 찍어서 보내주셨어요.",
    date: "2026-08-12",
    serviceName: "스페셜 미용",
  },
  {
    id: "rev-6",
    salonId: "salon-3",
    author: "한소희",
    petName: "구름",
    rating: 5,
    content:
      "15살 노령견인데 중간중간 쉬어가며 해주셔서 마음 놓고 맡겼어요.",
    date: "2026-08-16",
    serviceName: "약욕 & 피부 케어",
  },
  {
    id: "rev-7",
    salonId: "salon-3",
    author: "오지호",
    petName: "탄이",
    rating: 4,
    content: "저소음 드라이어라 그런지 아이가 훨씬 덜 무서워했어요.",
    date: "2026-08-09",
    serviceName: "기본 미용",
  },
  {
    id: "rev-8",
    salonId: "salon-4",
    author: "김하늘",
    petName: "몽이",
    rating: 5,
    content:
      "탄산 스파 받고 나서 털이 정말 부드러워졌어요. 몽이도 기분 좋아 보여요.",
    date: "2026-08-14",
    serviceName: "프리미엄 스파",
  },
  {
    id: "rev-9",
    salonId: "salon-4",
    author: "이도현",
    petName: "심바",
    rating: 5,
    content: "피부 트러블이 있었는데 스파 두 번 받고 많이 좋아졌습니다.",
    date: "2026-08-08",
    serviceName: "프리미엄 스파",
  },
  {
    id: "rev-10",
    salonId: "salon-4",
    author: "장미란",
    petName: "코코",
    rating: 4,
    content: "가격대가 있지만 그만큼 케어가 확실해요. 향도 은은하고 좋아요.",
    date: "2026-08-05",
    serviceName: "약욕 & 피부 케어",
  },
  {
    id: "rev-11",
    salonId: "salon-5",
    author: "서지우",
    petName: "감자",
    rating: 4,
    content: "당일 예약으로 급하게 갔는데 친절하게 잘해주셨어요. 가성비 좋아요.",
    date: "2026-08-13",
    serviceName: "부분 관리",
  },
  {
    id: "rev-12",
    salonId: "salon-5",
    author: "문채원",
    petName: "달이",
    rating: 4,
    content: "발톱이랑 귀청소만 받았는데 금방 끝나서 좋았어요.",
    date: "2026-08-07",
    serviceName: "부분 관리",
  },
  {
    id: "rev-13",
    salonId: "salon-6",
    author: "김하늘",
    petName: "보리",
    rating: 5,
    content:
      "무마취인데도 보리가 얌전히 있었다니 신기해요. 고양이 전문은 다르네요.",
    date: "2026-08-19",
    serviceName: "고양이 미용",
  },
  {
    id: "rev-14",
    salonId: "salon-6",
    author: "황인엽",
    petName: "치즈",
    rating: 5,
    content:
      "장모종이라 엉킨 털이 많았는데 아프지 않게 잘 풀어주셨어요. 감사합니다.",
    date: "2026-08-10",
    serviceName: "고양이 미용",
  },
  {
    id: "rev-15",
    salonId: "salon-6",
    author: "안유진",
    petName: "나비",
    rating: 4,
    content: "낯가림 심한 아이인데 천천히 적응시켜 주셔서 좋았어요.",
    date: "2026-08-04",
    serviceName: "고양이 미용",
  },
  {
    id: "rev-16",
    salonId: "salon-1",
    author: "윤성빈",
    petName: "마루",
    rating: 5,
    content: "매번 여기만 와요. 아이 컨디션까지 체크해주는 세심함이 좋아요.",
    date: "2026-08-02",
    serviceName: "스페셜 미용",
  },
];

export const COUPONS: Coupon[] = [
  {
    id: "cpn-1",
    name: "10% 할인 쿠폰",
    desc: "전체 서비스 10% 할인",
    discountRate: 0.1,
    expiresAt: "2026-09-30",
  },
  {
    id: "cpn-2",
    name: "첫 방문 5,000원 할인",
    desc: "신규 미용실 첫 예약 시",
    discountRate: 0,
    expiresAt: "2026-10-31",
  },
  {
    id: "cpn-3",
    name: "스파 15% 할인",
    desc: "프리미엄 스파 전용",
    discountRate: 0.15,
    expiresAt: "2026-09-15",
  },
];

export const TIME_SLOTS = [
  "09:00",
  "10:00",
  "11:00",
  "13:00",
  "14:00",
  "15:00",
  "16:00",
  "17:00",
];

export function getServiceById(id: string | null) {
  return SERVICES.find((s) => s.id === id) ?? null;
}
export function getSalonById(id: string | null) {
  return SALONS.find((s) => s.id === id) ?? null;
}
export function getGroomerById(id: string | null) {
  return GROOMERS.find((g) => g.id === id) ?? null;
}
export function getGroomersBySalon(salonId: string) {
  return GROOMERS.filter((g) => g.salonId === salonId);
}
export function getReviewsBySalon(salonId: string) {
  return REVIEWS.filter((r) => r.salonId === salonId);
}
